# Generated by Django 5.1.5 on 2025-01-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200510_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, help_text='Size: 1920x570', null=True, upload_to=''),
        ),
    ]
