# Generated by Django 5.1.6 on 2025-02-15 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_slide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('save_info', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_image', models.ImageField(upload_to='payment_images/')),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.useraddress')),
            ],
        ),
    ]
