# Generated by Django 5.1.6 on 2025-02-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_apartment_address_billingaddress_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='zip',
        ),
    ]
