# Generated by Django 5.1.6 on 2025-03-01 17:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_billingaddress_zip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='user_address',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='billing_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_method',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_image',
            field=models.ImageField(upload_to='payment_proofs/'),
        ),
    ]
